# Project information
site_name: Evgeniy Pogrebnyak (EPo)
site_url: https://epogrebnyak.github.io/
site_author: Evgeny Pogrebnyak
site_description: >-
  Economics, code and writing.

nav:
  - Home: index.md
  - Reading List: reading-list.md

theme:
  name: material
  palette:
    primary: light blue

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
